version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app:cached
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app:cached
    user: "${UID}:${GID}"
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local
